/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.0-51-g2d9b1ad-dirty

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: CommsTester.xdd
        File Version: 1

        Created:      8/31/2021 1:33:29 PM
        Created By:   
        Modified:     9/3/2021 10:24:03 AM
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: CommsTester
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_RPDO 2


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1F82 127


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint64_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
    } x1601_RPDOMappingParameter;
    uint8_t x1F82_requestNMT_sub0;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1005 &OD->list[2]
#define OD_ENTRY_H1006 &OD->list[3]
#define OD_ENTRY_H1007 &OD->list[4]
#define OD_ENTRY_H1014 &OD->list[5]
#define OD_ENTRY_H1015 &OD->list[6]
#define OD_ENTRY_H1017 &OD->list[7]
#define OD_ENTRY_H1018 &OD->list[8]
#define OD_ENTRY_H1019 &OD->list[9]
#define OD_ENTRY_H1200 &OD->list[10]
#define OD_ENTRY_H1400 &OD->list[11]
#define OD_ENTRY_H1401 &OD->list[12]
#define OD_ENTRY_H1600 &OD->list[13]
#define OD_ENTRY_H1601 &OD->list[14]
#define OD_ENTRY_H1F80 &OD->list[15]
#define OD_ENTRY_H1F82 &OD->list[16]
#define OD_ENTRY_H2000 &OD->list[17]
#define OD_ENTRY_H2001 &OD->list[18]
#define OD_ENTRY_H2002 &OD->list[19]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[2]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[3]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[4]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[5]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[6]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[7]
#define OD_ENTRY_H1018_identity &OD->list[8]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[9]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[10]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[11]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[12]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[13]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[14]
#define OD_ENTRY_H1F80_NMTStartup &OD->list[15]
#define OD_ENTRY_H1F82_requestNMT &OD->list[16]
#define OD_ENTRY_H2000_serialNumber &OD->list[17]
#define OD_ENTRY_H2001_lowPrecisionTemperature &OD->list[18]
#define OD_ENTRY_H2002_humidity &OD->list[19]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = NULL;\
    (config).ENTRY_H1A00 = NULL;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
